--- 
title: "Analyse Statistique M2 IGAST"
author: 'PC '
date: "`r Sys.Date()`"
documentclass: book
bibliography:
- book.bib
- packages.bib
biblio-style: apalike
link-citations: yes
description: "Ce cours collecte le contenu des diapositives des cours d'analyse statistique
  du M2 IGAST dans une forme plus proche du document. Le contenu est plus «rédigé»
  que celui des diapositives  Une version PDF et une version HTML sont proposées."
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    lib_dir: "book_assets"
  bookdown::pdf_book:
    keep_tex: yes
---


<!-- sequence pour compiler  -->
<!-- options(knitr.duplicate.label = "allow" -->
<!-- setwd("~/dev/page_Chercheur_LASTIG/pchapron_homepage/resources/bookdown_cours_stats") -->
<!-- rmarkdown::render_site(output_format = 'bookdown::gitbook', encoding = 'UTF-8') -->


# Préambule {-}

Ce document s'adresse en priorité aux étudiants du Master 2 IGAST de l'ENSG, dans le cadre du Module intitulé "Analyse Statistique", dirigé par Ana-Maria Olteanu-Raimond. 


## Programme du cours et Contenu {-}


Ce cours comporte une introduction générale pour situer les statistiques qui y sont abordées. 
Dans cette introduction, on parle beaucoup d'analyse spatiale, parce que c'est dans ce contexte que les rudiments de statistiques exposés ici vont etre utilisés par les étudiant.e.s du M2 IGAST, mais aucune technique purement spatiale n'est abordée ici. 



Le programme stricto-sensu  est le suivant :

Analyse Univariée: 

 - Vocabulaire
 - Description de distribution : indicateurs de tendance centrale, quantiles, dispersion , symétrie , applatissement 

Analyse Bivariée: 

 - regression linéaire : R2, p-value 
 - corrélation : r de Pearson , rho de Spearman, hypothèse nulle
 - Test du Chi 2 : Construction du tableau d'effectif théorique, calcul du Chi 2 , hypothèse nulle


Le reste, c'est du bonus ! 


## Reférences {-}

Pour constituer ce cours, j'ai utilisé les références suivantes: 

- Cours M2 IGAST 2018 d'Ana-Maria Olteanu-Raimond 
- Cours M2 IGAST 2017 d'Élodie Buard 
- Probabilités, analyse de données et statistiques , Gilbert Saporta, Editions TECHNIP, 2011
- l'excellent cours de Hadrien Commenges  https://gitlab.huma-num.fr/hcommenges/cours_statcomplet/-/raw/master/cours_statcomplet.pdf
- Nombreuses ressources en ligne, parmi lesquelles : 
    - http://www.foad-mooc.auf.org/IMG/pdf/424B_-Application_des_methodes_statistiques_d_analyse.pdf
    - http://www.itse.be/statistique2010/co/Module_statistique_FSP.html

J'ai également fait un usage immodéré de Wikipedia, Google, et StackOverflow

Pour les principes de la visualisation, 
j'essaye de suivre quelques uns des conseils prodigués par Claus O. Wilke dans son ouvrage [Fundamentals of Data Visualization]( https://clauswilke.com/dataviz/)


## Ressources pour l'apprentissage du langage R {-}

R est un langage qui s'apprend «au fil de l'eau», en trouvant des exemples de manipulations et des réponses à des questions sur des forums et sites spécialisé (Stackoverflow principalement). Cependant, l'étudiant.e IGAST désireuse d'aller droit au but et de manipuler des données spatiales avec R pourra se référer en priorité à :  


- R et espace https://framabook.org/r-et-espace/
- l'excellente formation à R du Ministère de la Transition Écologique et Solidaire : https://mtes-mct.github.io/parcours-r/ notamment le module 7 : « Analyse spatiale »
- la présentation du package `sf` sur https://r-spatial.github.io/sf/articles/sf1.html 
- le livre https://rcarto.github.io/carto_avec_r/ très complet pour la cartographie.


